# Generated by Django 5.2.8 on 2025-12-01 04:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Servicio', 'verbose_name_plural': 'Servicios'},
        ),
        migrations.AlterModelOptions(
            name='technicalreport',
            options={'verbose_name': 'Reporte Técnico', 'verbose_name_plural': 'Reportes Técnicos'},
        ),
        migrations.AddField(
            model_name='client',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización'),
        ),
        migrations.AddField(
            model_name='technicalreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='technicalreport',
            name='signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/', verbose_name='Imagen de Firma'),
        ),
        migrations.AddField(
            model_name='technicalreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Actualización'),
        ),
        migrations.AddField(
            model_name='technicalreport',
            name='warranty_period',
            field=models.CharField(blank=True, help_text='Ej: 3 meses, 1 año', max_length=100, verbose_name='Garantía'),
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.TextField(blank=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='client',
            name='company',
            field=models.CharField(blank=True, max_length=100, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=20, unique=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='client',
            name='type',
            field=models.CharField(choices=[('contract', 'Contrato TI'), ('punctual', 'Servicio Puntual')], default='punctual', max_length=20, verbose_name='Tipo de Cliente'),
        ),
        migrations.AlterField(
            model_name='service',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.client', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En Progreso'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='service',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to=settings.AUTH_USER_MODEL, verbose_name='Técnico'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='service',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Actualización'),
        ),
        migrations.AlterField(
            model_name='technicalreport',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='technicalreport',
            name='diagnosis',
            field=models.TextField(verbose_name='Diagnóstico'),
        ),
        migrations.AlterField(
            model_name='technicalreport',
            name='interventions',
            field=models.TextField(verbose_name='Intervenciones'),
        ),
        migrations.AlterField(
            model_name='technicalreport',
            name='parts_used',
            field=models.TextField(blank=True, verbose_name='Repuestos Utilizados'),
        ),
        migrations.AlterField(
            model_name='technicalreport',
            name='recommendations',
            field=models.TextField(blank=True, verbose_name='Recomendaciones'),
        ),
        migrations.AlterField(
            model_name='technicalreport',
            name='service',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='services.service', verbose_name='Servicio'),
        ),
        migrations.AlterField(
            model_name='technicalreport',
            name='signature',
            field=models.CharField(blank=True, max_length=100, verbose_name='Firma (Nombre)'),
        ),
        migrations.AlterField(
            model_name='technicalreport',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('final', 'Final')], default='draft', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='technicalreport',
            name='technician',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Técnico'),
        ),
    ]
