# Generated by Django 5.2.8 on 2025-12-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_client_options_alter_service_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha del Servicio'),
        ),
    ]
