# Generated by Django 5.2.8 on 2025-11-15 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('in_use', 'En Uso'), ('maintenance', 'En Mantenimiento'), ('damaged', 'Dañado')], default='available', max_length=20)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('purchase_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
