# Generated by Django 5.2.8 on 2025-12-01 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quote',
            options={'verbose_name': 'Cotización', 'verbose_name_plural': 'Cotizaciones'},
        ),
        migrations.AlterField(
            model_name='quote',
            name='client_email',
            field=models.EmailField(max_length=254, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='client_name',
            field=models.CharField(max_length=100, verbose_name='Nombre del Cliente'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='client_phone',
            field=models.CharField(max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='description',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='estimated_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo Estimado'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('sent', 'Enviada'), ('accepted', 'Aceptada'), ('rejected', 'Rechazada')], default='pending', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Actualización'),
        ),
    ]
